/* SQL STATEMENTS TO CREATE A DATABASE (AND TABLES) FOR RASPBERRY LIFE TO USE WITH HIBERNATE */


CREATE DATABASE IF NOT EXISTS rbl_data;
CREATE TABLE logic (logic_id BIGINT(10) NOT NULL AUTO_INCREMENT, name VARCHAR(50) NULL DEFAULT NULL,PRIMARY KEY (logic_id));
CREATE TABLE actuator (actuator_id BIGINT(10) NOT NULL AUTO_INCREMENT, name VARCHAR(50) NULL DEFAULT NULL, PRIMARY KEY (actuator_id));
CREATE TABLE logic_initiator (actuator_id BIGINT(10) NOT NULL,
logic_id BIGINT(10) NOT NULL,
PRIMARY KEY (actuator_id, logic_id),
INDEX FK_LOGIC (logic_id),
CONSTRAINT FK_ACTUATOR FOREIGN KEY (actuator_id) REFERENCES actuator (actuator_id),
CONSTRAINT FK_LOGIC FOREIGN KEY (logic_id) REFERENCES logic (logic_id));
